version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./registered_mcps:/app/registered_mcps
      - ./tunnel_logs:/app/tunnel_logs
      - ./contracts:/app/contracts
      - ./backend/app/db.json:/app/app/db.json  
    env_file:
      - ./backend/.env

  listener:
    build:
      context: ./backend
      dockerfile: Dockerfile.listener
    volumes:
      - ./registered_mcps:/app/registered_mcps
      - ./tunnel_logs:/app/tunnel_logs
      - ./contracts:/app/contracts
      - ./backend/app/db.json:/app/app/db.json  # 👈 MOUNT db.json
    env_file:
      - ./backend/.env